[tool.poetry]
name = "azure-product-bot-kb-updater"
version = "0.0.1"
description = ""
authors = ["Tim Meyers"]

[tool.poetry.dependencies]
python = "^3.8"
azure-cognitiveservices-knowledge-qnamaker = "^0.3.0"
azure-functions = "^1.6.0"
azure-data-scraper = {url = "https://files.pythonhosted.org/packages/e9/dc/86eb2b6be87437753c69c6a5f49120e9cfbc69dd587843514a32fb34d2aa/azure_data_scraper-0.1.6a0.tar.gz"}

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
yapf = "^0.30.0"
coverage = "^5.5"
pytest-cov = "^2.11.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
